# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser-simple.yaml

variables:
  description: "GPT-4 on the command line"
  github_url: "https://github.com/charmbracelet/mods"
  maintainer: "Toby Padilla <toby@charm.sh>"
  brew_commit_author_name: "Toby Padilla"
  brew_commit_author_email: "toby@charm.sh"
