Output mods.gif

Set Height 900
Set Width 1600
Set Framerate 24

Type@150ms `mods -M`
Sleep 500ms
Enter
Sleep 250ms

Down
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Up
Sleep 150ms
Down
Sleep 150ms
Down
Sleep 150ms
Up
Sleep 150ms
Up
Sleep 150ms

Sleep 150ms
Type@150ms `/`
Sleep 250ms
Type@150ms `gro`
Sleep 500ms
Enter
Sleep 250ms

Down
Sleep 150ms
Down
Sleep 150ms
Enter
Sleep 250ms

Type@150ms `Hello world`
Sleep 500ms
Enter

Sleep 3s
