name: lint
on:
  push:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: golangci-lint command line arguments.
          args: --timeout=120s
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
